### ISSUE TITLE
Chunking support design

### ISSUE THREAD

**Issue by telsethag** [pnnl/proven-cluster#140]
Provide support for large message items, by breaking them into smaller messages prior to disclosure into exchange environment.

**Tasks**
- [ ] Enumerate message items that will support chunking
- [ ] Modify message item schemas to support chunking 
- [ ] Document overview of the chunking process
